#!/usr/bin/env bash

# https://github.com/onespaceman/menu-calc
# Calculator for use with rofi/dmenu(2)
# Copying to the clipboard requires xclip

usage() {
    echo "    $(tput bold)menu-calc$(tput sgr0)
    A calculator for Rofi/dmenu(2)
    
    Usage:
    = 4+2
    = (4+2)/(4+3)
    = 4^2
    = sqrt(4)
    = c(2)

    The answer can be copied to the clipboard and used for further calculations inside (or outside) Rofi/dmenu.

    If launched outside of Rofi/dmenu the expression may need quotation marks."
    exit
}

case $1 in
    -h|--help) usage ;;
esac

# Path to menu application
if [[ -n $(command -v rofi) ]]; then
    menu="$(command -v rofi) -dmenu -lines 3 ""$@"
elif [[ -n $(command -v dmenu) ]]; then
    menu="$(command -v dmenu) ""$@"
else
    echo >&2 "Rofi or dmenu not found"
    exit
fi

answer=$(echo "$@" | bc -l | sed '/\./ s/\.\{0,1\}0\{1,\}$//')

action=$(echo -e "Copy to clipboard\nClear\nClose" |
$menu -p "= $answer")

case $action in
    "Clear") $0 ;;
    "Copy to clipboard") echo -n "$answer" | xclip -selection clipboard ;;
    "Close") ;;
    "") ;;
    *) $0 "$answer $action" ;;
esac
