.TH menu-calc 1
.SH NAME
menu-calc \- A calculator for
.BR rofi (1)
/
.BR dmenu (1) .

.SH SYNOPSIS
\fB=\fR [\fB-h\fR] [\fB<bc-math-expression>\fR] [\fB--dmenu=<dmenu_executable>\fR] [-- \fB<rofi/dmenu-parameters>\fR]

.SH DESCRIPTION
.PP
.BR menu-calc
uses
.BR bc (1)
as the backend and will accept any operations
.BR bc (1)
is able to do.
The answer can be copied to the clipboard and used for further calculations
inside (or outside) of
.BR rofi (1)
/
.BR dmenu (1) .
If launched outside of
.BR rofi (1)
/
.BR dmenu (1)
the expression may need quotation marks.
.PP
To launch directly into the calculator, rofi/dmenu parameters can be passed to
.BR menu-calc .

.SH EXAMPLES
.TP
Launch directly into the calculator passing -location 2 -width 100 to rofi/dmenu.
.B = -- -location 2 -width 100
.TP
Launch menu-calc and force use of dmenu.
.B = --dmenu=dmenu
.TP
Examples of performing math operations in menu-calc:
.B = 4^2
.TP
.RE
.B = sqrt(4)
.TP
.RE
.B = (4+2)/(4+3)
.TP
Bind \fBdmenu\fR(1) with a variety of parameters to F4 in \fBi3wm\fR(1).
.B bindsym F4 exec = --dmenu=dmenu -- -i -fn 'Isoveka Term 10' -dim 0.5 -l 3

.SH OPTIONS
.TP
.B \-h
show help
.TP
.B <bc-math-expression>
Parameters to be passed to
.BR bc (1) .
.TP
.B --dmenu=<dmenu_executable>
Set the dmenu-compatible executable. This can be used to force menu-calc to use
dmenu or rofi or some other dmenu-like executable.
.TP
.B <rofi/dmenu-parameters>
Parameters to be passed to
.BR rofi (1)
/
.BR dmenu (1) .

.SH AUTHOR
Jonathan Sumner Evans <sumner.evans98 at gmail dot com>

.SH "SEE ALSO"
.BR rofi (1),
.BR dmenu (1),
.BR bc (1)
