#!/usr/bin/env bash
# See EOF for Copyright notice

usage() {
    cat <<__EOF__
Usage: $0 [OPTION]... [QUERY]... [-- [MENU_OPTION]...]
A qalc frontend for menus like rofi, bemenu, and dmenu.

With no QUERY, initialize blank. MENU_OPTION appends options to the default
options for the menu.

  -m, --menu=MENU   run MENU as the menu. Defaults to rofi, bemenu, or dmenu if
                    available
  -g, --gui=PROG    run PROG when opening in GUI. Defaults to qalculate-gtk or
                    qalculate-qt if available
  -n, --no-opts     disable default options for menu program
  -h, --help        display this help and exit

Full documentation: man qalcmenu.1
__EOF__
}


# Process CLI options
temp="$(getopt -n "$0" -o '-h,m:,n,g:' -l 'help,menu:,no-opts,gui:' -- "$@")"

case $? in
    0) ;;
    1)
        usage
        exit 2 ;;
    *)
        echo 'Fatal error parsing options' >&2
        exit 127 ;;
esac

eval set -- "$temp"
unset temp

# Set default options
opts_menu=0
opts_menu_=''
opts_no_opts=0
opts_query=0
opts_query_=()
opts_gui=0
opts_gui_=''

# Read options
while true; do
    case "$1" in
        -h|--help)
            usage
            shift
            exit 1 ;;
        -m|--menu)
            opts_menu=1
            opts_menu_="$2"
            shift 2
            continue ;;
        -n|--no-opts)
            opts_no_opts=1
            shift 1
            continue ;;
        -g|--gui)
            opts_gui=1
            opts_gui_="$2"
            shift 2
            continue ;;
        --)
            shift
            break ;;
        *)
            opts_query=1
            opts_query_+=("$1")
            shift
            continue ;;
    esac
done


# Parse options
if [ "$opts_menu" -gt 0 ]; then
    menu="$opts_menu_"
elif command -v rofi >/dev/null; then
    menu=rofi
elif command -v bemenu >/dev/null; then
    menu=bemenu
elif command -v dmenu >/dev/null; then
    menu=dmenu
else
    echo 'No menu found or specified' >&2
    exit 2
fi


if [ "$opts_gui" -gt 0 ]; then
    gui="$opts_gui_"
elif command -v qalculate-gtk >/dev/null; then
    gui=qalculate-gtk
elif command -v qalculate-qt >/dev/null; then
    gui=qalculate-qt
else
    gui=''
fi


if [ "$opts_no_opts" -gt 0 ]; then
    moptions=()
elif [ "$(basename "$menu")" = rofi ]; then
    moptions=(-dmenu -p {})
elif [ "$(basename "$menu")" = bemenu ]; then
    moptions=(-p {} -cl 4 -W 0.2)
else
    moptions=(-p {})
fi
moptions+=("$@")

if [ "$opts_query" -gt 0 ]; then
    query="${opts_query_[*]}"
else
    query=''
fi

actions="Copy to clipboard"
if [ -n "$gui" ]; then
    actions+="\nOpen in GUI"
fi
actions+="\nClear\nClose"

# Event loop
while true; do
    # Grab answer
    if [ -n "$query" ]; then
        answer="$(echo "$query" | qalc +u8 -color=never -terse |
            awk '!/^>/ && !/^$/ {gsub(/^[ \t]+|[ \t]+$/, "", $0); print}')"
    else
        answer=''
    fi

    # Prompt user
    moptions_prompt=()
    for arg in "${moptions[@]}"; do
        _answer="$answer"
        [ -n "$_answer" ] && _answer=" $_answer"
        moptions_prompt+=("${arg//\{\}/=$_answer}")
    done

    if ! action=$(echo -e "$actions" | "$menu" "${moptions_prompt[@]}")
    then
        exit 3
    fi

    # Take action
    case "$action" in
        'Clear') query='' ;;
        'Open in GUI') exec "$gui" "$answer" ;;
        'Copy to clipboard') wl-copy -n "$answer" ;;
        'Close') exit 0 ;;
        *) query="$answer $action" ;;
    esac
done


# qalcmenu: A qalc frontend for menus like rofi, bemenu, and dmenu.
# Copyright (C) 2023  MithicSpirit
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
